---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: dkozlov.com/storage-operator:testing
    custom_resource_azure: "{{ lookup('file', '/'.join([deploy_dir, 'crds/dkozlov_v1alpha1_storage_azure_cr.yaml'])) | from_yaml }}"
    custom_resource_gcp: "{{ lookup('file', '/'.join([deploy_dir, 'crds/dkozlov_v1alpha1_storage_gcp_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the dkozlov.com/v1alpha1.Storage
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/dkozlov_v1alpha1_storage_azure_cr.yaml'])) }}"
  - name: Create the dkozlov.com/v1alpha1.Storage
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/dkozlov_v1alpha1_storage_gcp_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='dkozlov.com', api_version='v1alpha1', kind='Storage', namespace=namespace, resource_name=custom_resource_azure.metadata.name) }}"
  
  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='dkozlov.com', api_version='v1alpha1', kind='Storage', namespace=namespace, resource_name=custom_resource_gcp.metadata.name) }}"

  - name: Wait 40s for reconciliation to run
    k8s_facts:
      api_version: 'v1alpha1'
      kind: 'Storage'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource_azure.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10
  
  - name: Wait 40s for reconciliation to run
    k8s_facts:
      api_version: 'v1alpha1'
      kind: 'Storage'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource_gcp.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
